import "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import "./style/style.css";
import "./component/populer-carousel.js";
import "./component/app-bar.js";
import "./component/link-upcoming.js";
import "./component/link-nowplaying.js";
import "./component/link-popular.js";
import main from './view/main.js';
main();