import "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import "./style/style.css";
import "./component/populer-carousel.js";
import "./component/app-bar.js";
import "./component/movie-list.js";
import "./component/upcoming-list.js";
import "./component/populer-list.js";
import main from './view/main.js';
main();